name: Arxivist (Short)

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour

jobs:
  call-core:
    uses: ./.github/workflows/core.yml
    secrets: inherit
    with:
      search-arxiv: false
      search-scholar: false